services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
      - /vault:/vault
    ports:
      - 7878:7878
    restart: unless-stopped
networks: {}
