services:
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    env_file:
      - .env
    ports:
      - 5055:5055
    volumes:
      - ./config:/app/config
    restart: unless-stopped
